info:
  component: Config Samples
endpoints:
  restart:
    enabled: true
logging:
  levels:
    org.springframework.boot.env.PropertySourcesLoader: TRACE
    org.springframework.web: DEBUG
spring:
  application:
    name: spring-cloud-eureka-feign-client
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/